increased the version number in the DESCRIPTION because with r933 of BayesX I get the error below. To avoid this one can set -r 932 in the svn co line of boostrap.sh.
g++ -I/usr/share/R/include -DNDEBUG   -Ibayesxsrc/. -I"bayesxsrc/bib"  -I"bayesxsrc/alex"  -I"bayesxsrc/adaptiv"  -I"bayesxsrc/andrea"  -I"bayesxsrc/dag"  -I"bayesxsrc/graph"  -I"bayesxsrc/mcmc"  -I"bayesxsrc/psplines"  -I"bayesxsrc/samson"  -I"bayesxsrc/leyre"  -I"bayesxsrc/structadd" -D__BUILDING_GNU -D__BUILDING_LINUX -DTEMPL_INCL_DEF -D_MSC_VER2 -DNO_TEMPLATE_FRIENDS -DINCLUDE_REML -DINCLUDE_MCMC    -fpic  -O3 -pipe  -g  -c bayesxsrc/structadd/FC_predict.cpp -o bayesxsrc/structadd/FC_predict.o
bayesxsrc/structadd/FC_predict.cpp: In member function 'void MCMC::FC_predict::get_predictor()':
bayesxsrc/structadd/FC_predict.cpp:191:65: error: 'loglikelihood' was not declared in this scope
bayesxsrc/structadd/FC_predict.cpp:193:65: error: 'loglikelihood' was not declared in this scope
make: *** [bayesxsrc/structadd/FC_predict.o] Error 1
ERROR: compilation failed for package 'BayesXsrc'
* removing '/home/zeileis/lib/R/BayesXsrc'
* restoring previous '/home/zeileis/lib/R/BayesXsrc'




git-svn-id: svn://svn.r-forge.r-project.org/svnroot/bayesr@313 edb9625f-4e0d-4859-8d74-9fd3b1da38cb